// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj2a8V39wfwnytqEApqchCGDFpeDwcw7w',
    appId: '1:500871114974:web:615029ab54549d8e68d24f',
    messagingSenderId: '500871114974',
    projectId: 'campus-notify-651ff',
    authDomain: 'campus-notify-651ff.firebaseapp.com',
    storageBucket: 'campus-notify-651ff.firebasestorage.app',
    measurementId: 'G-Y9F2VNVRTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD30D4aMPmuuDdX5yZ3FHIihjDfPNeEx0w',
    appId: '1:500871114974:android:d6c2b8a24c8d999968d24f',
    messagingSenderId: '500871114974',
    projectId: 'campus-notify-651ff',
    storageBucket: 'campus-notify-651ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNUYasBUwYOlfhgMC4rCWpVC9PbgIQBwE',
    appId: '1:500871114974:ios:056755c861fac86068d24f',
    messagingSenderId: '500871114974',
    projectId: 'campus-notify-651ff',
    storageBucket: 'campus-notify-651ff.firebasestorage.app',
    iosBundleId: 'com.example.campusNotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNUYasBUwYOlfhgMC4rCWpVC9PbgIQBwE',
    appId: '1:500871114974:ios:056755c861fac86068d24f',
    messagingSenderId: '500871114974',
    projectId: 'campus-notify-651ff',
    storageBucket: 'campus-notify-651ff.firebasestorage.app',
    iosBundleId: 'com.example.campusNotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj2a8V39wfwnytqEApqchCGDFpeDwcw7w',
    appId: '1:500871114974:web:9cab1f06463d79b568d24f',
    messagingSenderId: '500871114974',
    projectId: 'campus-notify-651ff',
    authDomain: 'campus-notify-651ff.firebaseapp.com',
    storageBucket: 'campus-notify-651ff.firebasestorage.app',
    measurementId: 'G-77R8Q8QQ7V',
  );
}
